### PR TITLE
Update chapter2.txt

### PR DESCRIPTION
**Pull request by AshutoshK11**
/// leave a comment why i am doing making these changes

### CODE REVIEW

**Comment by AshutoshK11** [comment]
greate jon Ashutoshk11

**Comment by AshutoshK11** [comment]
> /// leave a comment why i am doing making these changes

welldone!!

**Review by AshutoshK11 — COMMENTED** [review]
Great job!

**Review by AshutoshCV — COMMENTED** [review]
Great job!!

**Pull request closed without merging**
